"""empty message

Revision ID: 44b3da3e2b52
Revises: 
Create Date: 2022-08-09 23:15:23.462286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b3da3e2b52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.add_column('allstudents', sa.Column('student_id', sa.Integer(), nullable=False))
    op.alter_column('allstudents', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('allstudents', 'post_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('allstudents', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allstudents', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('allstudents', 'post_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('allstudents', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('allstudents', 'student_id')
    op.create_table('student',
    sa.Column('student_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('post_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('student_id', name='student_pkey')
    )
    # ### end Alembic commands ###
